# Auto-generated by asn1ate v.0.6.0 from device_identity.asn
# (last modified on 2019-01-16 07:51:45.614578)

from pyasn1.type import univ, char, namedtype, namedval, tag, constraint, useful


class DeviceIdentityInfo(univ.Sequence):
    pass


DeviceIdentityInfo.componentType = namedtype.NamedTypes(
    namedtype.NamedType('wifiESSID', char.UTF8String()),
    namedtype.NamedType('wifiUsername', char.UTF8String()),
    namedtype.NamedType('wifiPassword', char.UTF8String()),
    namedtype.NamedType('wifiAuthType', char.UTF8String()),
    namedtype.NamedType('wifiAuthCert', univ.OctetString()),
    namedtype.NamedType('targetHost', char.UTF8String()),
    namedtype.NamedType('targetPort', univ.Integer()),
    namedtype.NamedType('deviceId', univ.Integer()),
    namedtype.NamedType('serverCaRoot', univ.OctetString()),
    namedtype.NamedType('identityCertChain', univ.SequenceOf(componentType=univ.OctetString()))
)


class Signature(univ.Sequence):
    pass


Signature.componentType = namedtype.NamedTypes(
    namedtype.NamedType('r', univ.Integer()),
    namedtype.NamedType('s', univ.Integer())
)


class DeviceIdentityBundle(univ.Sequence):
    pass


DeviceIdentityBundle.componentType = namedtype.NamedTypes(
    namedtype.NamedType('identityInfo', DeviceIdentityInfo()),
    namedtype.NamedType('identityInfoSignature', Signature())
)


