# Auto-generated by asn1ate v.0.6.0 from device_identity.asn
# (last modified on 2018-12-06 23:46:07.047296)

from pyasn1.type import univ, char, namedtype, namedval, tag, constraint, useful


class DeviceIdentityInfo(univ.Sequence):
    pass


DeviceIdentityInfo.componentType = namedtype.NamedTypes(
    namedtype.NamedType('wifiESSID', char.UTF8String().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('wifiPassword', char.UTF8String().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.NamedType('targetHost', char.UTF8String().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.NamedType('targetPort', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.NamedType('deviceId', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('identityCertChain', univ.SequenceOf(componentType=univ.BitString()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5)))
)


class Signature(univ.Sequence):
    pass


Signature.componentType = namedtype.NamedTypes(
    namedtype.NamedType('r', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('s', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
)


class DeviceIdentityBundle(univ.Sequence):
    pass


DeviceIdentityBundle.componentType = namedtype.NamedTypes(
    namedtype.NamedType('identityInfo', DeviceIdentityInfo().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 0))),
    namedtype.NamedType('identityInfoSignature', Signature().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 1)))
)


