DeviceIdentity
    { iso org(3) dod(6) internet(1) private(4) enterprise(1) twsided(46690) huffer(8) toluene(1) identity(1) }
    DEFINITIONS AUTOMATIC TAGS ::=
BEGIN


-- ECC signature, based on X9.64, containing (r, s). The algorithm and the
-- type of key are pre-negotiated based on the use case.
Signature ::= SEQUENCE {
    -- Signature r
    r BIT STRING,
    -- Signature s
    s BIT STRING
}

-- Contains the actual device identity information that is to be used
-- in managing and connecting to the target.
DeviceIdentityInfo ::= SEQUENCE {
    -- The ESSID we are to connect to
    wifiESSID UTF8String,

    -- The password for the network, supporting WPA2-PSK
    wifiPassword UTF8String,

    -- The target host IP address or hostname to connect to
    targetHost UTF8String,

    -- The target port, TCP connections using TLS
    targetPort INTEGER,

    -- Our unique device identifier
    deviceId INTEGER,

    -- The identity certificate chain for this device. This is an array of certificates,
    -- the first being the certificate representing the device, all the way up to the
    -- root. The root must match one of the trusted roots for the device.
    identityCertChain SEQUENCE OF BIT STRING
}

-- A signed bundle containing all the important identity information for this device
DeviceIdentityBundle ::= SEQUENCE {
    -- This device's identity info
    identityInfo DeviceIdentityInfo,
    -- Signature, from a trusted authority, for this device's identity information
    identityInfoSignature Signature
}

END
